services:
  - type: web
    name: clip-clasificador
    env: python
    plan: free
    region: oregon
    buildCommand: pip3 install -r requirements.txt
    startCommand: python3 app3.py
    envVars: []
    autoDeploy: true
